### ISSUE TITLE
Module not found: Error: Can't resolve 'swagger-schema-official/schema'

### ISSUE THREAD

**Issue by Thavaprakash** [apigee-127/sway#163] opened 2018-01-18 14:55 UTC
Hi ,
I'm getting below error. Please help me to get rid of this error.
npm version: "1.0.0"
node version: v8.9.1
npm version: 5.5.1

```
ERROR in ./node_modules/sway/lib/validation/validators.js
Module not found: Error: Can't resolve 'swagger-schema-official/schema' in '/home/project/node_modules/sway/lib/validation'
 @ ./node_modules/sway/lib/validation/validators.js 31:20-61
 @ ./node_modules/sway/lib/types/api.js
 @ ./node_modules/sway/index.js
 @ ./node_modules/swagger-node-runner/index.js
 @ ./node_modules/swagger-express-mw/lib/index.js
```

**Comment by whitlockjc** [comment] 2018-01-18 17:25
I cannot reproduce this.  I just installed `sway` into a new project and used it without issue.

**Comment by Thavaprakash** [comment] 2018-01-18 18:31
HI @whitlockjc ,
Thanks for your prompt reply, Actually I'm getting this error while run build using webpack after implementing Typescript in my project.

**Comment by whitlockjc** [comment] 2018-01-18 18:32
I'm not sure this is related to `sway` so I'm going to close this.  If you find out otherwise, let me know.

**Closed by whitlockjc** 2018-01-18 18:32 UTC

**Comment by dontry** [comment] 2018-11-11 01:36
I found the same error. I checked that the required module 'swagger-schema-official/schema' is missing in node_modules.
