### ISSUE TITLE
Only resolve local references during second pass

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#123] opened 2017-01-18 22:52 UTC
Sway does two passes of a document when resolving references, one to identify/resolve remote references and a second to identify/resolve local references.  Unfortunately, if any of the remote references fail to resolve the second pass _(as written right now)_ will attempt to re-resolve those failed remote references and will likely fail because the `json-refs` options are not prepared for resolving remote references.
To solve this we need to update https://github.com/apigee-127/sway/blob/master/index.js#L189 to actually filter out all non-local references like this:

```js
      // Resolve all references (Should only resolve locals now since the remote references are resolved)
      cOptions.jsonRefs.filter = function (refDetails) {
        return refDetails.type !== 'relative' && refDetails.type !== 'remote';
      };
```

Originally identified in #122.

**Comment by whitlockjc** [comment] 2017-01-19 17:24
Here is the little snippet used to test things: https://github.com/apigee-127/sway/issues/122#issuecomment-273840433

**Comment by noahdietz** [comment] 2017-07-31 23:26
With what is in master I can't reproduce this. The bug is definitely present in 1.0.0 but that doesn't have `json-refs` 3.0.0 which I'm thinking handles this case?

I can add a test for this just for posterity but otherwise I think this issue can be closed.

**Comment by noahdietz** [comment] 2017-08-01 17:48
Nevermind, I can reproduce with `master`. I think the spec I was using previously was being weird.

I copied the above snippet to the spot you indicated and the errors went away.

**Comment by noahdietz** [comment] 2017-08-02 19:34
and now i realize that I think this change breaks other tests because of #124 and the fact that the errors from both passes aren't being merged, and only the results from the second pass are being reported.

**Closed** 2017-12-02 03:43 UTC
Labels: in progress
