### ISSUE TITLE
An example of validator and generator for custom formats

### ISSUE THREAD

**Issue by amarzavery** [apigee-127/sway#127] opened 2017-01-30 17:09 UTC
We have a format named "uuid". I would like to add support for this while generating fake data.
[json-schema-faker](https://github.com/json-schema-faker/json-schema-faker#custom-formats) supports this. However, I was not able to find any plugin/hook to register validator and generator for the format.

I looked into the tests folder for an example but couldnt find one. 

Can you provide an example of how to 
- hook up a validator and generator for custom formats?

**Comment by whitlockjc** [comment] 2017-01-30 17:11
This is a duplicate of #100.

**Closed by whitlockjc** 2017-01-30 17:11 UTC
