### ISSUE TITLE
Sway matches first path always even if there might be a "better matching" path, intended or not?

### ISSUE THREAD

**Issue by daddy-cool** [apigee-127/sway#90] opened 2016-07-21 16:24 UTC
Let's say I have two paths in my Swaggerfile:
`/{id}` 
and
`/count`

now if I post to `/count` Sway's getPath-method matches this to `/{id}` instead of `/count`.

If I move `/count` before `/{id}` in my Swaggerfile it matches everything correctly.
Is this intended behaviour or a bug?

Thanks!

**Comment by whitlockjc** [comment] 2016-07-22 15:34
It's not intended, this is a duplicate of #76.

**Closed by whitlockjc** 2016-07-22 15:34 UTC
