### ISSUE TITLE
Support for Custom validators

### ISSUE THREAD

**Issue by ArjunHariharan** [apigee-127/sway#162] opened 2017-12-14 15:49 UTC
Is there a way to add custom validator for the request/response objects?
Ex - URL and Timezone formats are not supported by Swagger which I would like to add in addition to the existing validations which swagger provides.

**Comment by whitlockjc** [comment] 2017-12-27 21:29
This is a duplicate of #100.

**Closed by whitlockjc** 2017-12-27 21:29 UTC
