### ISSUE TITLE
Support Descriminator

### ISSUE THREAD

**Issue by saharj** [apigee-127/sway#58] opened 2016-01-15 20:58 UTC
Apparently `descriminator` is something that has been added to json schema in swagger. 

Please support it in sway as well. 

For context please go to:
https://github.com/swagger-api/swagger-editor/issues/765

**Comment by whitlockjc** [comment] 2016-01-15 21:02
Thisbisba duplicate of #28.

**Closed by whitlockjc** 2016-01-15 21:02 UTC
