### ISSUE TITLE
Prerelease on npm

### ISSUE THREAD

**Issue by penx** [apigee-127/sway#173] opened 2018-02-15 17:27 UTC
It's coming up on 2 years since sway@1.0.0 was released to npm.

@whitlockjc any chance you could put the current master as a prerelease on npm?

I think this is all that's needed:

```
npm version prerelease
npm publish
```

It would help me a lot with building and releasing [tooling that requires a recent version of sway](https://github.com/penx/openapi-mock) 🙂

**Comment by whitlockjc** [comment] 2018-02-16 19:25
Any reason you can't use `apigee-127/sway@master`?

**Comment by penx** [comment] 2018-02-16 19:40
Our team's issue is that we need to `npm install` from our internal package repository rather than from npm directly and users won't have access to GitHub when this happens.

sway, swagger-node-runner etc. all need to be added to our internal package repository and at some point patched with the changes I have on my forks. As far as I can tell, the easiest way to do this would be to import a release candidate from npm and then use [patch-package](https://www.npmjs.com/package/patch-package) to apply any further changes I need.

If you're interested, I've raised PRs for the changes I've made in my forks and am tracking them here:
https://github.com/penx/openapi-mock/issues/5

Lastly thanks for your work on this 🙂

**Comment by jwalton** [comment] 2018-03-15 13:21
Could we even have a 1.1.0 release?  I'm using swagger-node-runner which relies on Sway.  Would be nice if I could get access to custom formats.

**Comment by whitlockjc** [comment] 2018-03-15 14:00
Crafting a `1.1.0` release right now should be possible but I'd need to figure out what things could be merged.  Do you see anything in the [release notes](https://github.com/apigee-127/sway/blob/master/RELEASE_NOTES.md#tbd) that would be breaking and require a `2.0.0` vs. a `1.1.0`?  `1.0.1` definitely isn't an option with everything in the release notes.

**Comment by whitlockjc** [comment] 2018-06-08 15:03
I'm going to treat this as a duplicate of #176 as we'll likely address this there.

**Closed by whitlockjc** 2018-06-08 15:03 UTC
