### ISSUE TITLE
Request or response validation does not fail if the payload contains properties in a different case

### ISSUE THREAD

**Issue by amarzavery** [apigee-127/sway#125] opened 2017-01-19 05:05 UTC
The swagger spec, defines all the model properties in **camelCase**. However, the example contains the data in **PascalCase**. 
Making up a simple example for explanation:
- swagger spec
```json5
  {
     . . .
    "definitions": {
      "ParentModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The id of the model."
          }
        }
      },
      "ChildModel": {
        "type": "object",
        "properties": {
          "entityType": {
            "type": "string",
            "description": "The mapping entity type. Valid values are \"Profile\" \"Interaction\" and \"Relationship\"."
          },
          "allOf": [
            { "$ref": "#/definitions/ParentModel" }
          ],
          "additionalProperties": false //Added this later on to tighten
        }
      }
    }
  }
  ```
- and the sample contained:
```json5
{
 "id": "SomeId",
  "EntityType": "Profile"
}
```
I expected Sway to catch this for me. However, it gave a thumbs up.

Actual swagger spec and sample data for reference:
- [Model definition](https://github.com/tjlvtao/azure-rest-api-specs/blob/master/arm-customer-insights/2016-01-01/swagger/customer-insights.json#L4227) in the swagger spec.
- [Corresponding sample data](https://github.com/tjlvtao/azure-rest-api-specs/blob/master/arm-customer-insights/2016-01-01/examples/KpiCreateOrUpdate.json#L37).

After exploring the source code a bit, found the z-schema validator in the helper module that Sway depends on.
I tried setting `additionalProperties` to `false`  for the **child model** (as mentioned in the comment in the above sample). 
- **Expectation**:
I expected that `allOf` is basically a **composition** so it should take the properties of the parent and the child, compose it and after setting additionalProperties to false, should not allow any other properties
- **Reality**:
However, I was amazed to find that it blew up by saying **`id is an additional property and is not allowed`**. Did not allow the properties of the parent model. 

I do understand that `allOf` & `additionalProperties` in `Swagger` [is different](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object) from how the `json` schema defines them. 

As per the specification:
> Swagger allows combining and extending model definitions using the allOf property of JSON Schema, in effect offering model composition. allOf takes in an array of object definitions that are validated independently but together compose a single object.

The specification talks about composition but does not talk about the validation of the composed model. I assume it seems to be understood that the composed model should also be validated.

- **Question/Expectation from the tool**:
As a tool that takes a **swagger as an input** and validates the structure of the model, it should **provide a mechanism** to _tighten the grip and process the [allof definition as mentioned in the swagger specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism)_.

What are your thoughts on this?

**Comment by whitlockjc** [comment] 2017-01-19 05:31
This is part of JSON Schema.  It is a composite but you can have conflicts and if one schema disallows a property, it will fail.  I just tested this with straight up JSON Schema and it fails as well.  I tested the following at https://json-schema-validator.herokuapp.com:

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "entityType": {
      "type": "string",
      "description": "The mapping entity type. Valid values are \"Profile\" \"Interaction\" and \"Relationship\"."
    }
  },
  "allOf": [
         {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The id of the model."
          }
        }
      }  
  ],
  "additionalProperties": false
}
```

**Payload**

```json
{
 "id": "SomeId",
  "EntityType": "Profile"
}
```

**Validation Results**

```json
[ {
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : ""
  },
  "instance" : {
    "pointer" : ""
  },
  "domain" : "validation",
  "keyword" : "additionalProperties",
  "message" : "object instance has properties which are not allowed by the schema: [\"EntityType\",\"id\"]",
  "unwanted" : [ "EntityType", "id" ]
} ]
```

So as you can see, Sway is just reporting what JSON Schema reports in this case.  I won't close this yet but it seems this is due to how JSON Schema works.

**Comment by amarzavery** [comment] 2017-01-19 06:39
This exactly proves my point. **id** is **not** an unwanted property. **E**ntityType definitely is unwanted, because the schema says that **e**ntityType is the property name. _(In a json object keys are case-sensitive)_.

> Sway is just reporting what JSON Schema reports in this case.

I agree that the tool is doing that. However, that is not enough. Because, swagger specification is more than a json schema.

To prove my point, please read [this excerpt](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object) from the swagger specification which is as follows:
> The following properties are taken from the JSON Schema definition but their definitions were **adjusted to the Swagger Specification**. Their definition is the same as the one from JSON Schema, only where the original definition references the JSON Schema definition, the Schema Object definition is used instead.
> - items
> - allOf
> - properties
> - additionalProperties

Later the spec, [explains allof] (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism)
> Swagger allows combining and extending model definitions using the allOf property of JSON Schema, in **effect offering model composition**. allOf takes in an array of object definitions that are validated independently but together **compose a single object**.


**So my question is**:
- `id` and `entityType` together compose the final object. So how can `id` be an unwanted property?

**Comment by whitlockjc** [comment] 2017-01-19 16:47
Well, I understand your frustration but even with Swagger's wording it is possible to have conflicting schemas.  Let's get @webron involved to see what he says.

**Comment by webron** [comment] 2017-01-19 20:03
I'm going to put the discussion on hold for one main reason:
```json
{
        "type": "object",
        "properties": {
          "entityType": {
            "type": "string",
            "description": "The mapping entity type. Valid values are \"Profile\" \"Interaction\" and \"Relationship\"."
          },
          "allOf": [
            { "$ref": "#/definitions/ParentModel" }
          ],
          "additionalProperties": false //Added this later on to tighten
        }
      }
```
That's not even a valid JSON Schema, Swagger or no Swagger. You're defining a *property* called `allOf` and trying to define it as an array of something. That's not how you use `allOf` and that's not a valid syntax.

**Comment by whitlockjc** [comment] 2017-01-19 20:04
Good catch @webron, I didn't even catch that.

**Comment by amarzavery** [comment] 2017-01-19 21:43
I am sorry for making up an incorrect example. I was trying to simplify things and probably put stuff in the wrong place ;).

- Here is the schema:
```
{
  "type": "object",
  "properties": {
    "entityType": {
      "type": "string",
      "description": "The mapping entity type. Valid values are \"Profile\" \"Interaction\" and \"Relationship\"."
    }
  },
  "allOf": [
    { "$ref": "#/definitions/ParentModel" }
  ],
  "additionalProperties": false,
  "definitions": {
    "ParentModel": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The id of the model."
        }
      }
    }
  }
}
```
- Here is the data:
```
{
  "id": "SomeId",
  "EntityType": "Profile"
}
```
- Here is the validation result:
```
[ {
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : ""
  },
  "instance" : {
    "pointer" : ""
  },
  "domain" : "validation",
  "keyword" : "additionalProperties",
  "message" : "object instance has properties which are not allowed by the schema: [\"EntityType\",\"id\"]",
  "unwanted" : [ "EntityType", "id" ]
} ]
```

- Should `"id"` also be an **unwanted** property ?

**Comment by webron** [comment] 2017-01-19 22:34
Yes :( The `"additionalProperties": false` makes it so that it conflicts with the `allOf`. Not a Swagger issue but a JSON Schema one 😕

**Comment by johanste** [comment] 2017-01-19 23:09
One observation is that the OpenAPI specification explicitly says that neither the definition of allOf or additionalProperties are taken straight from the json schema specification, but rather that their meaning are modified to fit the needs of swagger. 

Off the top of my head, it would not be unreasonable to, given the the definition of allOf:

> allOf takes in an array of object definitions that are validated independently but together compose a single object.

interpret the composed single object (from a schema and validation perspective) as effectively having all the properties from all the schemas in the allOf array.

**Comment by webron** [comment] 2017-01-19 23:21
Having written the spec itself, the intent of the two things you bring up were:
1. The difference in `allOf` and `additionalProperties` is that their content is the Swagger Schema Object and not a regular JSON Schema (otherwise we allow people to 'escape' the boundaries). Beyond that, they behave the same.
2. The quote you mention is intended to help people who don't fully understand how JSON Schema works and assume `allOf` is a merge of schemas, and it is not. That's it. It doesn't change the behavior from JSON Schema, it explains it.

**Comment by johanste** [comment] 2017-01-19 23:29
My humble feedback on the specification is that, while the intent was to clarify the behavior, it did not help me get a better understanding - in fact, it made me look for the differences that weren't there. The explanation above is to me significantly more clear than what's currently in the spec. 

It may be helpful to create an annotated version of the specification where some of these clarifications are provided inline.

**Comment by webron** [comment] 2017-01-19 23:31
Well, hopefully it will be clearer in the next version of the spec, but the current one is not going to change. Hopefully, the behavior is clearer now though, and I'll be happy to answer any further questions.

**Comment by whitlockjc** [comment] 2017-01-20 16:48
Since things appear to be working as designed, I'm closing this.  Feel free to continue the discussion or to reopen if you feel it should be addressed again.

**Closed by whitlockjc** 2017-01-20 16:48 UTC

**Comment by amarzavery** [comment] 2017-01-20 18:05
@whitlockjc - This is one more reason, why I want the validator in helper.js to be exposed.
The function [createJSONValidator()](https://github.com/apigee-127/sway/blob/master/lib/helpers.js#L104)
```
function createJSONValidator () {
  var validator = new ZSchema({
  breakOnFirstError: false,
  ignoreUnknownFormats: true,
  reportPathAsArray: true
});
```
is creating an instance of ZSchema validator. Now, Z-schema validator has an option called [assumeAdditional](https://github.com/zaggino/z-schema#assumeadditional) which when set, assumes `additionalProperties: false` on the model schema in swagger. 

This helps me make the validation stricter. As a user, I should be able to fine tune the validator to my needs.

Can the validator instance be exported?
