### ISSUE TITLE
Error is thrown on duplicate keys in resolved remote references

### ISSUE THREAD

**Issue by MikeRalphson** [apigee-127/sway#137] opened 2017-03-30 11:55 UTC
I believe it is this [line](https://github.com/apigee-127/sway/blob/master/index.js#L175) responsible.

The error finally reported is not very indicative of the source of the problem:

>- code: UNRESOLVABLE_REFERENCE
  error: ptr must be a JSON Pointer
  message: 'Reference could not be resolved: ../examples/NameSpaces/SBNameSpaceList.json'
  path:
    - paths
    - '/subscriptions/{subscriptionId}/providers/Microsoft.ServiceBus/namespaces'
    - get
    - x-ms-examples
    - NameSpaceList
    - $ref

Would you accept a PR to add options of `{json: true}` to the `YAML.safeLoad()` call, possibly controlled by an option setting?

Real life example (this [PR](https://github.com/Azure/azure-rest-api-specs/pull/1083) refers).

> https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-servicebus/2015-08-01/swagger/servicebus.json

**Comment by whitlockjc** [comment] 2017-03-30 15:21
This is a duplicate of #131.

**Closed by whitlockjc** 2017-03-30 15:21 UTC

**Comment by MikeRalphson** [comment] 2017-03-30 15:27
> This is a duplicate of #131.

Only partially. The clobbering of the json-refs error message is one thing, but treating all resolved JSON content as YAML breaks the defined behaviour of JSON in that duplicate keys are ignored.

**Comment by whitlockjc** [comment] 2017-03-30 17:24
`js-yaml` _should_ be throwing an error whenever it attempts to load a document with duplicate keys: https://github.com/nodeca/js-yaml/commit/9ea29ec6aa5e48d3dff3eacf7582818643a0ab0c  I checked the release version and it's older than the one we're using.  I will do a quick check with `json-refs` to see if it's suppressing the error, a known issue.

**Comment by MikeRalphson** [comment] 2017-03-30 17:39
Thanks for the update. In my case the data being returned is JSON not YAML, and so the `js-yaml.safeLoad()` in strict mode is producing different results than a `JSON.parse()` would return. I still consider this less than optimal behaviour.

**Comment by whitlockjc** [comment] 2017-03-30 17:45
I've tracked it down.  There are three players here:

* `js-yaml`
* `json-refs`
* `sway`

Here are the results:

**Test YAML**

```yaml
---
definitions:
  Person:
    properties:
      age:
        type: integer
      age:
        type: string

```

**Test JS**

```js
var fs = require('fs');
var JsonRefs = require('json-refs');
var Sway = require('sway');
var YAML = require('js-yaml');

var docLocation = '/tmp/test.yaml';

function printBad (name, err) {
  console.error('Bad document (%s): %s', name, err.message);
}

function printGood (name) {
  console.log('Good document (%s)', name);
}

try {
  YAML.safeLoad(fs.readFileSync(docLocation, 'utf8'));

  printGood('js-yaml');
} catch (err) {
  printBad('js-yaml', err)
}

JsonRefs.findRefsAt(docLocation)
  .then(function () {
    printGood('json-refs');
  })
  .catch(function (err) {
    printBad('json-refs', err);
  });

Sway.create({definition: docLocation})
  .then(function () {
    printGood('sway');
  })
  .catch(function (err) {
    printBad('sway', err);
  });
```

**Test Output**
```
Bad document (js-yaml): duplicated mapping key at line 7, column -25:
          age:
          ^
Bad document (json-refs): Unexpected number in JSON at position 1
Bad document (sway): duplicated mapping key at line 7, column -25:
          age:
          ^
```

**Results**

It seems that if the duplicate key is in the root document, `js-yaml` and `sway` handle it just fine while `json-refs` seems to have some weird issue _(not sure what is up but I'll report it there and link this issue)_.  But, if the duplicate key is not in the root document and is instead in an included document, then `json-refs` is the one processing the document so it would be impacted by the weird bug.

As for the JSON vs. YAML portion of your last response, it's already reported here: https://github.com/whitlockjc/json-refs/issues/101  Long story short, I wanted to avoid having to _juggle_ parsing JSON vs. YAML and since `js-yaml` successfully parses both, it seemed like a quick win but it's not 100%.

**Comment by MikeRalphson** [comment] 2017-03-30 18:06
> As for the JSON vs. YAML portion of your last response, it's already reported here: whitlockjc/json-refs#101 Long story short, I wanted to avoid having to juggle parsing JSON vs. YAML and since js-yaml successfully parses both, it seemed like a quick win but it's not 100%.

Understand. At the moment [APIs.guru](https://github.com/apis-guru/openapi-directory) requires the use of a `sway` patched as per the original suggestion in this issue, but I don't really want to have to maintain forks of `api-spec-converter` and `sway`. But I can put off a decision on switching to another validator for a while until the situation on support for OpenAPI 3 becomes clearer.

**Comment by whitlockjc** [comment] 2017-03-30 18:40
PRs are welcome.
