### ISSUE TITLE
RangeError: Maximum call stack size exceeded with large YAML file

### ISSUE THREAD

**Issue by bosco-li** [apigee-127/sway#85] opened 2016-06-13 18:01 UTC
Hi there, we are getting a RangeError with this file -> https://dl.dropboxusercontent.com/u/14439503/huge.yaml

The stack seems to show the error is from this method -> https://github.com/apigee-127/sway/blob/master/index.js#L209-L211

We have a client waiting for this, really hope you can help with this, thank you so much!

**Comment by whitlockjc** [comment] 2016-06-13 19:31
I can reproduce this and I will look into this.

**Comment by bosco-li** [comment] 2016-06-13 19:33
@whitlockjc Thank you so much!

**Comment by whitlockjc** [comment] 2016-06-13 19:35
Initial digging I see that these are indeed circular:

```
#/definitions/OperationDefinitionParameter/allOf/1/properties/part/items
#/definitions/ParametersParameter/allOf/1/properties/part/items
#/definitions/ImplementationGuidePage/allOf/1/properties/page/items
#/definitions/QuestionnaireGroup/allOf/1/properties/group/items
#/definitions/QuestionnaireResponseGroup/allOf/1/properties/group/items
#/definitions/ContractTerm/allOf/1/properties/group/items
#/definitions/CompositionSection/allOf/1/properties/section/items
#/definitions/ValueSetConcept/allOf/1/properties/concept/items
#/definitions/ValueSetContains/allOf/1/properties/contains/items
```

I'm not sure why the circular handling isn't working but I will figure it out.

**Comment by whitlockjc** [comment] 2016-06-13 19:45
I have a fix but I'm trying to figure out why it works.  It should be working as-is so before I just commit this as _the_ fix, I need to check to see if it's really fixing the issue or working around it somehow.

**Comment by whitlockjc** [comment] 2016-06-13 20:41
I think this might be related to https://github.com/whitlockjc/json-refs/issues/82.

**Comment by whitlockjc** [comment] 2016-06-13 21:05
I think if json-refs was capable of finding **all** circulars, sway could just use the json-refs metadata.  Let me attempt to fix it there, I've got an idea.

**Comment by whitlockjc** [comment] 2016-06-14 01:54
I'm still working on this and will continue to until I get it fixed.  Once it's fixed, I'll release json-refs and sway with the fix.

**Comment by bosco-li** [comment] 2016-06-14 15:14
Thanks so much @whitlockjc!

**Comment by whitlockjc** [comment] 2016-06-14 17:59
I've got it fixed locally.  I will release a new version of json-refs and release a new version of sway with the new version of json-refs.

**Comment by whitlockjc** [comment] 2016-06-14 22:40
I've released a new version of json-refs.  I am now testing to see if this addresses your issue.  It seems to stop the `RangeError` but boy is it slow.  I'm trying to gather some metrics on it.

**Comment by whitlockjc** [comment] 2016-06-14 22:45
I think due to the large number of references you have, the approach in json-refs to fix https://github.com/whitlockjc/json-refs/issues/82 might not be performant enough.  I will likely need to spend more time with this.

**Comment by bosco-li** [comment] 2016-06-15 15:43
Thanks @whitlockjc for helping to push a new version :bow:.  How long does it take yours to finish?

I cleaned up the yaml a bit (sorry for missing the circular before), [here](https://dl.dropboxusercontent.com/u/14439503/cleaned.yaml) is the updated version.

Tried running Sway again seems to have stuck at [this line](https://dl.dropboxusercontent.com/u/14439503/cleaned.yaml).  I've let mine ran for a while now.

**Comment by whitlockjc** [comment] 2016-06-15 15:54
Which line?  The link you have is to your YAML.  I'm tracing now to see what is up also.

**Comment by whitlockjc** [comment] 2016-06-15 16:00
I created https://github.com/whitlockjc/json-refs/issues/87 to keep track of this.  Fixing https://github.com/whitlockjc/json-refs/issues/82 was kind of a brute force thing and it works fine with all of the test Swagger documents but for yours, it just crawls.  I'm tracing as well.

**Comment by whitlockjc** [comment] 2016-06-15 16:12
I added a cache so we do not pre-process potential circulars.  It seems to fix things but it makes identifying one of the circulars fail.  I'll get this sorted and come back when it's done.  Feel free to share anything you've got.

**Comment by whitlockjc** [comment] 2016-06-15 17:22
I've got it fixed.  I'm making some changes to the way in which json-refs resolves references.  Right now, finding references is fast.  Processing references to identify circulars is now fast.  Resolving references is fast enough but is missing a case and I think it's the way references are resolved.  I'll get it fixed, and this should address https://github.com/whitlockjc/json-refs/issues/87.

**Comment by whitlockjc** [comment] 2016-06-15 23:34
With the new code, there are still two circular references that do not get replaced properly.  I'm tracking this down.

**Comment by bosco-li** [comment] 2016-06-21 14:20
@whitlockjc did you get a chance to fix the two circular references problem?  Thanks again for looking into it.

**Comment by whitlockjc** [comment] 2016-06-22 15:49
I've not fixed it yet but I've been working on it.  I'll let you know when it's done, sorry for the delay.

**Comment by bosco-li** [comment] 2016-06-24 17:32
@whitlockjc Thanks again for helping, feel free to share the area you think there is a problem is too, I can help take a look.  We've a client waiting for this to work with them.

Thanks again for the help!

**Comment by whitlockjc** [comment] 2016-06-24 17:34
I've been working on it in all of my free time.  I've got a good solution, just finishing it up.  I needed to start fresh to avoid over-engineering it.

**Comment by bosco-li** [comment] 2016-07-11 19:23
Hi @whitlockjc, sorry I note that you are only doing this at your free time, I just wanted to see how is the progress and if anything I can help?

Thanks so much!

**Comment by whitlockjc** [comment] 2016-07-13 18:09
I've been at a conference and finishing a sprint so my time has been limited.  I've been working on it actively and I'm almost done.  Fixing this is making json-refs much faster and more complete.  I'm glad you ran into this issue, although I'm sorry it's taken so long fixing it.

**Comment by bosco-li** [comment] 2016-07-20 15:08
Hi @whitlockjc - np I understand and appreciate your effort, thank you for using your talents to create software that help the world!  Hopefully you can get the fix soon so this can unblock us and we can do more testings.  Thanks so much.

**Comment by bosco-li** [comment] 2016-08-10 16:03
@whitlockjc wanted to see if you have an update on this one please?  Thanks again for helping and understanding!

**Comment by whitlockjc** [comment] 2016-08-10 16:24
I was on vacation and have just gotten back.  It's on my radar, sorry for the delay.

**Comment by bosco-li** [comment] 2016-08-30 14:22
Hi @whitlockjc wanted to see if you have time on this one please?  Thanks!

**Comment by bosco-li** [comment] 2016-10-25 19:48
Hi @whitlockjc, it's been a while, wanted to get back on this if you'll fix this issue please?

Thanks so much.

**Comment by whitlockjc** [comment] 2016-10-31 16:01
I apologize and I'm on it.  :)

**Comment by bosco-li** [comment] 2016-12-19 21:17
Hi @whitlockjc are you still on this one?  Our test team found this and now our customer experience this one as well.

**Comment by bosco-li** [comment] 2016-12-19 21:18
Please do share your thought on the problem and where you plan to put in the fix as well.  So we can start looking into other options to get a fix.

**Comment by whitlockjc** [comment] 2016-12-20 16:17
I can start working on a branch to make this easier to collaborate.  Basically, I've rewritten the core logic so many times I can't tell you.  I just haven't had any time recently like I thought I would.  Would that help?

**Comment by BrighTide** [comment] 2017-02-14 02:18
Hey, the effect this problem us having on apigee-127/swagger-tools#39 is a bit of a blocker for us :( I can justify using some overtime to make a fix, if it's just a matter of throwing some dev time at some bullet points? Let me know :) (also, obligatory thanks for all the work you do with open api spec tooling!)

**Comment by whitlockjc** [comment] 2017-02-14 02:44
Sorry for the blocker, I'll be working on it tonight.  If I can't get it patched up within a day or so, I can see if I can get some help.

**Comment by BrighTide** [comment] 2017-02-14 03:32
No worries, and awesome sauce :) let me know

**Comment by BrighTide** [comment] 2017-02-19 23:07
Hey, so did you need any additional man power getting that fix out in the end?

**Comment by whitlockjc** [comment] 2017-02-21 17:08
Well, I just need to figure out how to manifest time.  ;)  All kidding aside, I'm 90% done with a rewrite of the resolver that has a huge performance benefit and fixes all known resolution bugs.  I should had been committing this to a branch so others could help but since I didn't, that's not possible so more people power wouldn't help.  I'll do better next time but know it's almost done.

**Comment by BrighTide** [comment] 2017-02-21 23:00
I'll hit up my local occult library, see if they've got any time stuff :D, and awesome. Thanks for all the hard work!

**Comment by whitlockjc** [comment] 2017-02-27 17:24
Alright, I'm really banging my head against the wall on this one.  If anyone wants to do some pair programming on this, please join me in: https://gitter.im/whitlockjc/json-refs

**Comment by whitlockjc** [comment] 2017-04-25 05:59
@bosco-li Sorry for the long delay but I've got a new version of `json-refs` that will improve performance and accuracy.  I'm not sure if you're still using this but if you are, let me know.  I'll be updating `sway` shortly to use the new release within the next few days.

**Comment by whitlockjc** [comment] 2017-04-25 06:10
`json-refs@v3.0.0` [has released](https://github.com/whitlockjc/json-refs/releases/tag/v3.0.0) and `sway` will be updated to include it.  Based on the test document @bosco-li provided, processing time went from over 48 minutes to under 2.2 seconds.  And everything is resolved and recorded as expected.

**Comment by bosco-li** [comment] 2017-05-05 15:57
Thank you!

**Comment by whitlockjc** [comment] 2017-05-05 16:07
I'm reopening until `sway` has been updated to use `json-refs@v3.0.0`.

**Comment by bosco-li** [comment] 2017-05-05 16:52
Thanks - do you know when will that happen?

**Comment by whitlockjc** [comment] 2017-05-05 18:10
ASAP. ;)  I've been working on Kubernetes stuff this week, `sway` hopefully over the weekend.

**Comment by bosco-li** [comment] 2017-06-13 13:49
@whitlockjc do you have an estimate when there will be an update for `sway` to use `json-refs@v3.0` please?

Thanks.

**Comment by whitlockjc** [comment] 2017-06-13 22:58
No.  👎   But it's my top priority in my personal time at my keyboard.

**Comment by whitlockjc** [comment] 2017-07-08 04:31
`sway` was just updated to `json-refs@v3.0.0`.  I'm going to merge PRs and fix bugs before cutting a release.

**Closed by whitlockjc** 2017-07-08 04:31 UTC

**Comment by bosco-li** [comment] 2017-07-10 20:59
@whitlockjc thank you for this.  Are you going to publish the updates on npm please?

**Comment by whitlockjc** [comment] 2017-07-10 22:19
Yep, the work has already started.  All deps were updated, although I do think better `json-refs` support needs to be done.  I'm also fixing bug/feature requests and then cutting a release.

**Comment by bosco-li** [comment] 2017-07-12 15:44
Thanks @whitlockjc - do you have a timeline for cutting a release just so we know when to expect please?

**Comment by whitlockjc** [comment] 2017-07-12 15:53
No concrete ETA but I'm working on it in the evenings so it should be within a week or so.
