### ISSUE TITLE
circular references

### ISSUE THREAD

**Issue by sherpya** [apigee-127/sway#87] opened 2016-07-06 06:47 UTC
I have something like:

```
  A:
    properties:
      b:
        $ref: "#/definitions/B"
  B:
    properties:
      a:
        $ref: "#/definitions/A"
```

swagger tools silently drops validations from A, but the def is still usable,
sway says nothing when parsing the schema but then I get `UNRESOLVABLE_REFERENCE` when I try to use it.
It would be better not to drop circular references and handle them using a max depth, a common usage is depth 1, or at least ignore validation of `b` property of `A` instead of making `A` unusable/non validable (other properties)

**Comment by whitlockjc** [comment] 2016-07-06 16:04
This is a duplicate of #85 and will be addressed there.  As for how it works, swagger-tools and sway should work the same in how things are handled.  I think fixing #85 will end up with what you want.

**Closed by whitlockjc** 2016-07-06 16:04 UTC
