### ISSUE TITLE
request validation fails for optional parameters

### ISSUE THREAD

**Issue by snrbrnjna** [apigee-127/sway#60] opened 2016-02-05 14:51 UTC
`operation.validateRequest(req)` falsely fails for multiple reasons:
- when there's nothing said, wether a parameter is required and the param is missing, the validation fails with:
    +  `Cannot read property \'readUInt8\' of undefined` for strings
    + `Expected type boolean but found type undefined` for booleans
  the spec says it defaults to false.
    + ...
- when no mime type is defined via consumes

i was giving this library a try, because the swagger-tools [do not validate array-enums correctly](https://github.com/apigee-127/swagger-tools/issues/343).

**Comment by whitlockjc** [comment] 2016-02-05 15:29
I doubt it fails falsely as any runtime error, like the first, would be thrown.  As for the second, I'm not sure what you're saying there but it seems like an optional boolean is not defaulting to `false` like you'd expect.  The third...I don't know what that one is.  When there is no consumes, the request shouldn't fail.

**Comment by whitlockjc** [comment] 2016-02-05 15:29
As for swagger-tools not validating enums properly, I think your schema is wrong as I mentioned there.

**Comment by whitlockjc** [comment] 2016-02-05 17:40
I can reproduce these issues but here is my feedback:

* This is an issue and will be fixed
* Nothing in the specification says that an optional boolean defaults to `false`.  If you want to set a default value, use the `default` property.  But, I do think it's wrong to validate optional arguments without a value so I will fix this as well.
* I have no idea what you're talking about regarding consumes

Any information you can share on how to reproduce each of these would be ideal because all I can do is guess.

**Comment by whitlockjc** [comment] 2016-02-05 17:50
The first two issues you see are related to an issue with how we identify optional parameters.  Fixing one fixes both.  Commit incoming.

**Comment by whitlockjc** [comment] 2016-02-05 17:53
I cannot reproduce the last issue.  I tried with empty consumes at both the global and operation level, and with no consumes at all at the global and operation level.

**Comment by whitlockjc** [comment] 2016-02-05 17:56
Without more information, I cannot reproduce or fix the third issue you brought up.  As for the other two, they are fixed and will be released in `1.0.0`.

**Closed** 2016-02-05 17:55 UTC

**Comment by snrbrnjna** [comment] 2016-02-08 13:11
thanks for your prompt answer - and sorry, i cannot reproduce the last issue neither.
